name: KCloud
favicon: null
layout_spectrum: 0.00810148031450808
typography_spectrum: 0.851133507443592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6957275248132646
  lightness: 0.14666406996548176
  saturation: 0.330965326866135
  rhythmicContrast: 0.30567108117975295
purpose: []
